id: I664A369C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T12:46:47+00:00'
last_modified: '2022-06-07T12:09:23.342875+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181173
  title: སྔ་འགྱུར་གཡག་ཟེའི་གཏེར་སྟོན་བདེ་མཆོག་གླིང་པའི་གཏེར་ཆོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '8735':
      image_group_id: I1KG16340
      title: Volume 1 of snga 'gyur g.yag ze'i gter ston bde mchog gling pa'i gter
        chos/
      total_pages: 702
      order: 1
      base_file: 8735.txt
    4DE6:
      image_group_id: I1KG16341
      title: Volume 2 of snga 'gyur g.yag ze'i gter ston bde mchog gling pa'i gter
        chos/
      total_pages: 1016
      order: 2
      base_file: 4DE6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
